global using DiscordBotLibrary.ChannelResources;
global using DiscordBotLibrary.GuildMemberResources;
global using DiscordBotLibrary.GuildScheduledEventResources;
global using DiscordBotLibrary.PresenceUpdateResources;
global using DiscordBotLibrary.StageInstanceResources;
global using DiscordBotLibrary.GuildCreateEventResources;
global using DiscordBotLibrary.OverwriteResources;
global using DiscordBotLibrary.ThreadMemberResources;
global using DiscordBotLibrary.ActivityResources;
global using System.Text.Json.Serialization;

